# Created by: Ken Moore <ken@pcbsd.org>

PORTNAME=	 ayras
PORTVERSION= 1.6.2
PORTEPOCH=	 3
CATEGORIES=	 x11

MAINTAINER=	lbartoletti@FreeBSD.org
COMMENT=	Lumina Desktop Environment (meta-port)

LICENSE=	BSD3CLAUSE

RUN_DEPENDS=	ayras-core>=0:x11/ayras-core \
		ayras-coreutils>=0:x11/ayras-coreutils \
		lumina-archiver>=0:deskutils/lumina-archiver \
		lumina-calculator>=0:deskutils/lumina-calculator \
		lumina-fileinfo>=0:deskutils/lumina-fileinfo \
		lumina-fm>=0:deskutils/lumina-fm \
		lumina-mediaplayer>=0:deskutils/lumina-mediaplayer \
		lumina-pdf>=0:deskutils/lumina-pdf \
		lumina-photo>=0:deskutils/lumina-photo \
		lumina-screenshot>=0:deskutils/lumina-screenshot \
		lumina-textedit>=0:deskutils/lumina-textedit

USES=		metaport

CONFLICTS_INSTALL=	lumina-1.2.*

.include <bsd.port.mk>
