# This port is a modification of GBI by GhostBSD.
PORTNAME=potabi-installer
PORTVERSION=9.6
CATEGORIES=sysutils
MASTER_SITES= https://github.com/Potabi/${PORTNAME}/archive
MAINTINER=kai@potabi.com
COMMENT=Potabi Installer is a fork of the GhostBSD "GBI" tool.
LICENSE=BSD
RUNDEPENDS= pc-sysinstall>0:sysutils/pc-sysinstall
USE_GITHUB=yes
GH_ACCOUNT=Potabi
USES=python gnome
USE_PYTHON=distutils noflavors
USE_GNOME=pygobject3
.include <bsd.port.mk>
